// Raw SQL below only interpolates Guids/identifiers generated by the tests themselves.
#pragma warning disable EF1002
using System.Text.Json;
using Aethera.Domain;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Aethera.Api.Tests;

/// <summary>Runs against a real PostgreSQL (see <see cref="RequiresDatabaseFactAttribute"/>).</summary>
public sealed class PersistenceIntegrationTests(TestDatabaseFixture database) : IClassFixture<TestDatabaseFixture>
{
    private static readonly DateTimeOffset Now = new(2026, 10, 3, 12, 0, 0, TimeSpan.Zero);

    private sealed record Seed(Guid OrgId, Guid ProjectId, Guid EnvId, Guid ServerId, Guid UserId);

    private static string Unique(string prefix) => prefix + "-" + Guid.NewGuid().ToString("N")[..12];

    private async Task<Seed> SeedBaseAsync()
    {
        using var lease = database.NewContext();
        var db = lease.Db;
        var org = new Organization { Name = "Turn One", Slug = Unique("org") };
        var user = new User($"{Unique("u")}@example.com", "Owner");
        var project = new Project { Organization = org, Name = "Turn One", Slug = "turn-one" };
        var env = new ProjectEnvironment { Project = project, Name = "Production", Slug = "production", IsProduction = true };
        var server = new Server { Organization = org, Name = Unique("srv"), Host = "203.0.113.10" };
        db.AddRange(org, user, project, env, server);
        await db.SaveChangesAsync();
        return new Seed(org.Id, project.Id, env.Id, server.Id, user.Id);
    }

    private static Secret NewSecret(Guid orgId, string name)
    {
        var secret = new Secret { OrganizationId = orgId, Name = name };
        secret.AddVersion([1, 2, 3], new byte[12], [9], new byte[12], masterKeyVersion: 1, Now);
        return secret;
    }

    private static Application NewApp(Seed seed, string? slug = null) => new()
    {
        EnvironmentId = seed.EnvId,
        ServerId = seed.ServerId,
        Name = "API",
        Slug = slug ?? Unique("api"),
    };

    private async Task<Guid> SeedAppAsync(Seed seed)
    {
        using var lease = database.NewContext();
        var app = NewApp(seed);
        lease.Db.Add(app);
        await lease.Db.SaveChangesAsync();
        return app.Id;
    }

    private static async Task<DbUpdateException> AssertConstraintAsync(Func<Task> action, string sqlState)
    {
        var ex = await Assert.ThrowsAsync<DbUpdateException>(action);
        var pg = Assert.IsType<PostgresException>(ex.InnerException);
        Assert.Equal(sqlState, pg.SqlState);
        return ex;
    }

    private const string UniqueViolation = "23505";
    private const string CheckViolation = "23514";

    [RequiresDatabaseFact]
    public async Task Migration_CreatesExpectedTables()
    {
        using var lease = database.NewContext();
        var tables = await lease.Db.Database
            .SqlQueryRaw<string>("SELECT table_name AS \"Value\" FROM information_schema.tables WHERE table_schema = 'public'")
            .ToListAsync();

        foreach (var expected in new[]
        {
            "organizations", "users", "organization_members", "teams", "team_members", "api_tokens", "user_sessions",
            "projects", "environments", "servers", "join_tokens", "certificate_authorities", "agent_certificates",
            "workloads", "git_sources", "build_configs", "image_sources", "compose_sources", "git_credentials",
            "webhook_endpoints", "webhook_deliveries", "workload_ports", "environment_variables", "secrets", "secret_versions",
            "volumes", "networks", "workload_networks", "domains", "registries", "deployments", "deployment_steps", "builds",
            "jobs", "log_chunks", "audit_events", "resource_events", "idempotency_records", "settings", "metric_samples", "images",
        })
            Assert.Contains(expected, tables);
    }

    [RequiresDatabaseFact]
    public async Task ProjectEnvironmentApplicationDeployment_GraphRoundTrips()
    {
        var seed = await SeedBaseAsync();
        Guid appId, deploymentId;

        using (var lease = database.NewContext())
        {
            var db = lease.Db;
            var secret = NewSecret(seed.OrgId, "GITHUB_TOKEN");
            secret.EnvironmentId = seed.EnvId;
            var credential = new GitCredential
            {
                OrganizationId = seed.OrgId, Name = Unique("gh"), Kind = GitCredentialKind.Token, Provider = GitProvider.GitHub, Secret = secret,
            };
            var app = NewApp(seed);
            app.SourceKind = ApplicationSourceKind.Git;
            app.Runtime.RestartPolicy = RestartPolicy.OnFailure;
            app.Runtime.DeploymentStrategy = DeploymentStrategies.LowDowntime;
            app.Runtime.CpuLimit = 1.5;
            app.Runtime.MemoryLimitBytes = 512L * 1024 * 1024;
            app.Runtime.HealthCheck = new HealthCheckConfig { Type = HealthCheckType.Http, Path = "/health", Port = 8080, Retries = 5 };
            app.GitSource = new GitSource
            {
                Provider = GitProvider.GitHub, RepositoryUrl = "https://github.com/turn-one/api.git", Branch = "main",
                AutoDeploy = true, GitCredential = credential,
            };
            app.BuildConfig = new BuildConfig
            {
                Engine = BuildEngines.Dockerfile, DockerfilePath = "Dockerfile",
                BuildArgs = new Dictionary<string, string> { ["NODE_ENV"] = "production" },
            };
            app.Ports.Add(new WorkloadPort { ContainerPort = 8080, IsHttp = true });
            app.EnvironmentVariables.Add(new EnvironmentVariable { Key = "DATABASE_URL", Secret = secret, IsBuildTime = false });
            app.EnvironmentVariables.Add(new EnvironmentVariable { Key = "NODE_ENV", Value = "production", IsBuildTime = true });
            app.Volumes.Add(new Volume { Name = "api-data", MountPath = "/data", BackupEnabled = true });
            app.Domains.Add(NewDomain(seed, "API.Turn-One.Example"));
            db.Add(app);
            await db.SaveChangesAsync();
            appId = app.Id;

            var number = app.AllocateDeploymentNumber();
            var deployment = Deployment.Queue(app.Id, seed.EnvId, seed.ServerId, number, DeploymentTrigger.Webhook, Now,
                DeploymentStrategies.LowDowntime);
            deployment.CommitSha = "0123456789abcdef";
            deployment.Ref = "main";
            deployment.TriggeredByUserId = seed.UserId;
            deployment.Start("""{"runtime":{"restartPolicy":"OnFailure"}}""", Now.AddSeconds(1));
            deployment.BeginStep(DeploymentStep.Source, Now.AddSeconds(1));
            deployment.CompleteStep(DeploymentStep.Source, Now.AddSeconds(2));
            deployment.BeginStep(DeploymentStep.Build, Now.AddSeconds(2));
            deployment.Builds.Add(new Build { Engine = BuildEngines.Dockerfile, CacheHit = true });
            deployment.CompleteStep(DeploymentStep.Build, Now.AddSeconds(20), """{"cacheHit":true}""");
            deployment.ImageRef = "aethera/api:abc";
            deployment.ContainerIds = ["c0ffee"];
            deployment.MarkRunning(Now.AddSeconds(30));
            app.CurrentDeploymentId = deployment.Id;
            db.Add(deployment);
            db.Add(new ImageRecord
            {
                WorkloadId = app.Id, DeploymentId = deployment.Id, ServerId = seed.ServerId,
                Repository = "aethera/api", Tag = "abc", SizeBytes = 1234,
            });
            await db.SaveChangesAsync();
            deploymentId = deployment.Id;
        }

        using (var lease = database.NewContext())
        {
            var db = lease.Db;
            var app = await db.Set<Application>()
                .Include(a => a.GitSource)
                .Include(a => a.BuildConfig)
                .Include(a => a.Ports)
                .Include(a => a.EnvironmentVariables)
                .Include(a => a.Volumes)
                .Include(a => a.Domains)
                .SingleAsync(a => a.Id == appId);

            Assert.Equal(RestartPolicy.OnFailure, app.Runtime.RestartPolicy);
            Assert.Equal(DeploymentStrategies.LowDowntime, app.Runtime.DeploymentStrategy);
            Assert.Equal(1.5, app.Runtime.CpuLimit);
            Assert.Equal(512L * 1024 * 1024, app.Runtime.MemoryLimitBytes);
            Assert.Equal(HealthCheckType.Http, app.Runtime.HealthCheck.Type);
            Assert.Equal("/health", app.Runtime.HealthCheck.Path);
            Assert.Equal(5, app.Runtime.HealthCheck.Retries);
            Assert.Equal(1, app.DeploymentSequence);
            Assert.Equal(deploymentId, app.CurrentDeploymentId);
            Assert.NotNull(app.GitSource);
            Assert.True(app.GitSource!.AutoDeploy);
            Assert.NotNull(app.GitSource.GitCredentialId);
            Assert.Equal("production", app.BuildConfig!.BuildArgs["NODE_ENV"]);
            Assert.Single(app.Ports);
            Assert.Equal(2, app.EnvironmentVariables.Count);
            Assert.Equal("api.turn-one.example", Assert.Single(app.Domains).Hostname);
            Assert.Equal("api-data", Assert.Single(app.Volumes).Name);

            var deployment = await db.Deployments.Include(d => d.Builds).Include(d => d.Steps).SingleAsync(d => d.Id == deploymentId);
            Assert.Equal(DeploymentStatus.Running, deployment.Status);
            Assert.Equal(DeploymentStrategies.LowDowntime, deployment.Strategy);
            Assert.Equal(
                [DeploymentStep.Source, DeploymentStep.Build, DeploymentStep.Running],
                deployment.Steps.Select(x => x.Step).OrderBy(x => x));
            Assert.Equal(StepStatus.Succeeded, deployment.Steps.Single(x => x.Step == DeploymentStep.Build).Status);
            Assert.True(deployment.IsRollbackPoint);
            Assert.Equal(1, deployment.Number);
            Assert.Equal(["c0ffee"], deployment.ContainerIds);
            Assert.Equal(seed.UserId, deployment.TriggeredByUserId);
            Assert.True(Assert.Single(deployment.Builds).CacheHit);
            using var snapshot = JsonDocument.Parse(deployment.ConfigSnapshotJson);
            Assert.Equal("OnFailure", snapshot.RootElement.GetProperty("runtime").GetProperty("restartPolicy").GetString());

            // Enums are stored as readable strings, ids are UUIDv7.
            var raw = await db.Database
                .SqlQueryRaw<string>($"SELECT status AS \"Value\" FROM deployments WHERE id = '{deploymentId}'")
                .SingleAsync();
            Assert.Equal("running", raw);
            Assert.Equal(7, deploymentId.Version);
        }
    }

    private static WorkloadDomain NewDomain(Seed seed, string hostname, string path = "/")
    {
        var domain = new WorkloadDomain { ServerId = seed.ServerId, PathPrefix = path };
        domain.SetHostname(hostname);
        return domain;
    }

    [RequiresDatabaseFact]
    public async Task ServiceAndApplication_ShareOneTable_WithDiscriminator()
    {
        var seed = await SeedBaseAsync();
        Guid serviceId, appId;
        using (var lease = database.NewContext())
        {
            var service = new Service
            {
                EnvironmentId = seed.EnvId, ServerId = seed.ServerId, Name = "Postgres", Slug = Unique("pg"),
                TemplateKey = "postgres", TemplateVersion = "17", Image = "postgres:17", ConfigJson = """{"database":"app"}""",
            };
            var app = NewApp(seed);
            lease.Db.AddRange(service, app);
            await lease.Db.SaveChangesAsync();
            serviceId = service.Id;
            appId = app.Id;
        }

        using (var lease = database.NewContext())
        {
            var all = await lease.Db.Workloads.Where(w => w.Id == serviceId || w.Id == appId).OrderBy(w => w.Slug).ToListAsync();
            Assert.Equal(2, all.Count);
            var service = Assert.IsType<Service>(all.Single(w => w.Id == serviceId));
            Assert.Equal("postgres:17", service.Image);
            using var cfg = JsonDocument.Parse(service.ConfigJson);
            Assert.Equal("app", cfg.RootElement.GetProperty("database").GetString());
            Assert.IsType<Application>(all.Single(w => w.Id == appId));

            var kinds = await lease.Db.Database
                .SqlQueryRaw<string>($"SELECT kind AS \"Value\" FROM workloads WHERE id IN ('{serviceId}','{appId}') ORDER BY kind")
                .ToListAsync();
            Assert.Equal(["application", "service"], kinds);
        }
    }

    [RequiresDatabaseFact]
    public async Task Server_RolesFactsAndStatusesRoundTrip()
    {
        var seed = await SeedBaseAsync();
        Guid id;
        using (var lease = database.NewContext())
        {
            var server = new Server
            {
                OrganizationId = seed.OrgId, Name = Unique("srv"), Host = "10.0.0.5", Roles = [ServerRole.Master, ServerRole.Build],
                Transport = ServerTransport.Agent, PublicIp = "198.51.100.7", AgentVersion = "0.1.0",
            };
            server.Facts.Os = "Ubuntu 24.04";
            server.Facts.CpuCores = 8;
            server.Facts.MemoryBytes = 16L * 1024 * 1024 * 1024;
            server.RecordHeartbeat(Now, DockerStatus.Running);
            lease.Db.Add(server);
            await lease.Db.SaveChangesAsync();
            id = server.Id;
        }

        using (var lease = database.NewContext())
        {
            var server = await lease.Db.Servers.SingleAsync(s => s.Id == id);
            Assert.Equal([ServerRole.Master, ServerRole.Build], server.Roles);
            Assert.Equal("Ubuntu 24.04", server.Facts.Os);
            Assert.Equal(8, server.Facts.CpuCores);
            Assert.Equal(16L * 1024 * 1024 * 1024, server.Facts.MemoryBytes);
            Assert.Equal(AgentStatus.Connected, server.AgentStatus);
            Assert.Equal(DockerStatus.Running, server.DockerStatus);
            Assert.Equal(Now, server.LastHeartbeatAt);

            var withBuildRole = await lease.Db.Servers.Where(s => s.Roles.Contains(ServerRole.Build)).Select(s => s.Id).ToListAsync();
            Assert.Contains(id, withBuildRole);
        }
    }

    [RequiresDatabaseFact]
    public async Task NonUtcOffsetsAreNormalisedToUtc()
    {
        var seed = await SeedBaseAsync();
        var local = new DateTimeOffset(2026, 10, 3, 15, 0, 0, TimeSpan.FromHours(3));
        Guid id;
        using (var lease = database.NewContext())
        {
            var token = new ApiToken
            {
                OrganizationId = seed.OrgId, CreatedByUserId = seed.UserId, Name = "ci", Prefix = Unique("aeth"),
                SecretHash = new byte[ApiToken.SecretHashLength], Scopes = ["deployments:write", "servers:read"], ExpiresAt = local,
            };
            lease.Db.Add(token);
            await lease.Db.SaveChangesAsync();
            id = token.Id;
        }

        using (var lease = database.NewContext())
        {
            var token = await lease.Db.ApiTokens.SingleAsync(t => t.Id == id);
            Assert.Equal(local, token.ExpiresAt);
            Assert.Equal(TimeSpan.Zero, token.ExpiresAt!.Value.Offset);
            Assert.Equal(["deployments:write", "servers:read"], token.Scopes);
        }
    }

    [RequiresDatabaseFact]
    public async Task EnvironmentVariableKey_IsUniquePerWorkload()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);

        using var lease = database.NewContext();
        lease.Db.Add(new EnvironmentVariable { WorkloadId = appId, Key = "PORT", Value = "80" });
        await lease.Db.SaveChangesAsync();

        using var second = database.NewContext();
        second.Db.Add(new EnvironmentVariable { WorkloadId = appId, Key = "PORT", Value = "81" });
        await AssertConstraintAsync(() => second.Db.SaveChangesAsync(), UniqueViolation);
    }

    [RequiresDatabaseFact]
    public async Task EnvironmentVariable_CannotHoldBothValueAndSecret()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);

        using var lease = database.NewContext();
        var secret = NewSecret(seed.OrgId, Unique("s"));
        lease.Db.Add(new EnvironmentVariable { WorkloadId = appId, Key = "X", Value = "plain", Secret = secret });
        await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), CheckViolation);
    }

    [RequiresDatabaseFact]
    public async Task DomainHostname_IsUniqueAmongActiveRows_AndFreedBySoftDelete()
    {
        var seed = await SeedBaseAsync();
        var firstApp = await SeedAppAsync(seed);
        var secondApp = await SeedAppAsync(seed);
        var host = Unique("site") + ".example.com";

        Guid firstDomainId;
        using (var lease = database.NewContext())
        {
            var domain = NewDomain(seed, host);
            domain.WorkloadId = firstApp;
            lease.Db.Add(domain);
            await lease.Db.SaveChangesAsync();
            firstDomainId = domain.Id;
        }

        using (var lease = database.NewContext())
        {
            var duplicate = NewDomain(seed, host.ToUpperInvariant());
            duplicate.WorkloadId = secondApp;
            lease.Db.Add(duplicate);
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }

        using (var lease = database.NewContext())
        {
            // Same host, different path prefix is a different route.
            var other = NewDomain(seed, host, "/docs");
            other.WorkloadId = secondApp;
            lease.Db.Add(other);
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            var first = await lease.Db.Domains.SingleAsync(d => d.Id == firstDomainId);
            first.MarkDeleted(Now);
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            var reused = NewDomain(seed, host);
            reused.WorkloadId = secondApp;
            lease.Db.Add(reused);
            await lease.Db.SaveChangesAsync(); // allowed again
        }
    }

    [RequiresDatabaseFact]
    public async Task DeploymentNumber_IsUniquePerWorkload()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);

        using (var lease = database.NewContext())
        {
            lease.Db.Add(Deployment.Queue(appId, seed.EnvId, seed.ServerId, 1, DeploymentTrigger.Manual, Now));
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(Deployment.Queue(appId, seed.EnvId, seed.ServerId, 1, DeploymentTrigger.Redeploy, Now));
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task SoftDeletedProjects_AreHiddenByDefault_AndSlugCanBeReused()
    {
        var seed = await SeedBaseAsync();
        var slug = Unique("proj");
        Guid id;
        using (var lease = database.NewContext())
        {
            var project = new Project { OrganizationId = seed.OrgId, Name = "Temp", Slug = slug };
            lease.Db.Add(project);
            await lease.Db.SaveChangesAsync();
            id = project.Id;
        }

        using (var lease = database.NewContext())
        {
            var project = await lease.Db.Projects.SingleAsync(p => p.Id == id);
            project.MarkDeleted(Now);
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            Assert.False(await lease.Db.Projects.AnyAsync(p => p.Id == id));
            Assert.True(await lease.Db.Projects.IgnoreQueryFilters().AnyAsync(p => p.Id == id && p.DeletedAt != null));

            lease.Db.Add(new Project { OrganizationId = seed.OrgId, Name = "Temp again", Slug = slug });
            await lease.Db.SaveChangesAsync();
        }
    }

    [RequiresDatabaseFact]
    public async Task ConcurrentUpdates_AreDetectedWithXmin()
    {
        var seed = await SeedBaseAsync();

        using var first = database.NewContext();
        using var second = database.NewContext();
        var a = await first.Db.Projects.SingleAsync(p => p.Id == seed.ProjectId);
        var b = await second.Db.Projects.SingleAsync(p => p.Id == seed.ProjectId);
        Assert.NotEqual(0u, a.RowVersion);

        a.Description = "from A";
        await first.Db.SaveChangesAsync();

        b.Description = "from B";
        await Assert.ThrowsAsync<DbUpdateConcurrencyException>(() => second.Db.SaveChangesAsync());
    }

    [RequiresDatabaseFact]
    public async Task UpdatedAt_IsStampedOnUpdate()
    {
        var seed = await SeedBaseAsync();
        using var lease = database.NewContext();
        var project = await lease.Db.Projects.SingleAsync(p => p.Id == seed.ProjectId);
        var before = project.UpdatedAt;

        await Task.Delay(20);
        project.Description = "changed";
        await lease.Db.SaveChangesAsync();

        Assert.True(project.UpdatedAt > before);
    }

    [RequiresDatabaseFact]
    public async Task Secret_AllowsAtMostOneScope_AndNamesAreUniquePerScope()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);

        Secret Make(string name) => NewSecret(seed.OrgId, name);

        using (var lease = database.NewContext())
        {
            var twoScopes = Make("both");
            twoScopes.ProjectId = seed.ProjectId;
            twoScopes.EnvironmentId = seed.EnvId;
            lease.Db.Add(twoScopes);
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), CheckViolation);
        }

        var name = Unique("TOKEN");
        using (var lease = database.NewContext())
        {
            lease.Db.Add(Make(name)); // org scope
            var scoped = Make(name);  // same name, workload scope: allowed
            scoped.WorkloadId = appId;
            lease.Db.Add(scoped);
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(Make(name)); // duplicate at org scope (NULLs compare equal)
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task WorkloadPort_IsUniquePerProtocol_AndPortRangeIsChecked()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);

        using (var lease = database.NewContext())
        {
            lease.Db.Add(new WorkloadPort { WorkloadId = appId, ContainerPort = 53, Protocol = PortProtocol.Tcp });
            lease.Db.Add(new WorkloadPort { WorkloadId = appId, ContainerPort = 53, Protocol = PortProtocol.Udp });
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(new WorkloadPort { WorkloadId = appId, ContainerPort = 70000 });
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), CheckViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task AuditEvents_AreAppendOnlyInTheDatabase()
    {
        var seed = await SeedBaseAsync();
        Guid id;
        using (var lease = database.NewContext())
        {
            var evt = new AuditEvent
            {
                OrganizationId = seed.OrgId, ActorType = AuditActorType.User, ActorUserId = seed.UserId, ActorLabel = "owner@example.com",
                Action = "deployment.created", ResourceType = "deployment", ResourceId = Guid.CreateVersion7(),
                MetadataJson = """{"trigger":"manual"}""", OccurredAt = Now,
            };
            lease.Db.Add(evt);
            await lease.Db.SaveChangesAsync();
            id = evt.Id;
        }

        using var raw = database.NewContext();
        var ex = await Assert.ThrowsAsync<PostgresException>(() =>
            raw.Db.Database.ExecuteSqlRawAsync($"UPDATE audit_events SET action = 'tampered' WHERE id = '{id}'"));
        Assert.Contains("append-only", ex.MessageText);
        Assert.Equal(1, await raw.Db.AuditEvents.CountAsync(e => e.Id == id && e.Action == "deployment.created"));
    }

    [RequiresDatabaseFact]
    public async Task JobClaim_FollowsAdr0004_SkipLockedPriorityAndLockKeys()
    {
        var type = Unique("test-job");
        var busyKey = Unique("app");
        var org = (await SeedBaseAsync()).OrgId;
        using (var lease = database.NewContext())
        {
            var running = new Job { OrganizationId = org, Type = type, LockKey = busyKey };
            running.Claim("other-worker", Now, TimeSpan.FromMinutes(1));
            lease.Db.AddRange(
                running,
                new Job { OrganizationId = org, Type = type, Priority = 0, RunAfter = Now.AddHours(-3) },
                new Job { OrganizationId = org, Type = type, Priority = 10, RunAfter = Now.AddHours(-2) },
                new Job { OrganizationId = org, Type = type, Priority = 5, RunAfter = Now.AddHours(-1) },
                new Job { OrganizationId = org, Type = type, Priority = 50, RunAfter = Now.AddHours(-1), LockKey = busyKey }, // blocked by the running job
                new Job { OrganizationId = org, Type = type, Priority = 100, RunAfter = Now.AddDays(1) }); // not due yet
            await lease.Db.SaveChangesAsync();
        }

        // The claim statement from ADR 0004 (type filter added to isolate this test).
        const string claim =
            "SELECT j.*, j.xmin FROM jobs j WHERE j.status = 'queued' AND j.type = {0} AND j.run_after <= {1} " +
            "AND (j.lock_key IS NULL OR NOT EXISTS (SELECT 1 FROM jobs r WHERE r.status = 'running' AND r.lock_key = j.lock_key)) " +
            "ORDER BY j.priority DESC, j.run_after, j.id FOR UPDATE SKIP LOCKED LIMIT 1";

        using var one = database.NewContext();
        using var two = database.NewContext();
        await using var txOne = await one.Db.Database.BeginTransactionAsync();
        await using var txTwo = await two.Db.Database.BeginTransactionAsync();

        var first = await one.Db.Jobs.FromSqlRaw(claim, type, Now).SingleAsync();
        var second = await two.Db.Jobs.FromSqlRaw(claim, type, Now).SingleAsync();

        Assert.Equal(10, first.Priority);
        Assert.Equal(5, second.Priority); // the row locked by the first worker was skipped, the blocked key was filtered

        first.Claim("worker-1", Now, TimeSpan.FromMinutes(1));
        second.Claim("worker-2", Now, TimeSpan.FromMinutes(1));
        await one.Db.SaveChangesAsync();
        await two.Db.SaveChangesAsync();
        await txOne.CommitAsync();
        await txTwo.CommitAsync();

        using var check = database.NewContext();
        var stored = await check.Db.Jobs.SingleAsync(j => j.Id == first.Id);
        Assert.Equal(JobStatus.Running, stored.Status);
        Assert.Equal("worker-1", stored.LockedBy);
        Assert.Equal(1, stored.Attempt);
    }

    [RequiresDatabaseFact]
    public async Task JobClaimIndex_IsAPartialIndexOnQueuedRows()
    {
        using var lease = database.NewContext();
        var def = await lease.Db.Database
            .SqlQueryRaw<string>("SELECT indexdef AS \"Value\" FROM pg_indexes WHERE indexname = 'ix_jobs_claim'")
            .SingleAsync();
        Assert.Contains("priority DESC", def);
        Assert.Contains("'queued'", def);
    }

    [RequiresDatabaseFact]
    public async Task JobIdempotencyKey_IsUniqueWhenSet()
    {
        var key = Unique("delivery");
        var org = (await SeedBaseAsync()).OrgId;
        using (var lease = database.NewContext())
        {
            lease.Db.Add(new Job { OrganizationId = org, Type = "application.deploy", IdempotencyKey = key });
            lease.Db.Add(new Job { OrganizationId = org, Type = "x" }); // null keys never collide
            lease.Db.Add(new Job { OrganizationId = org, Type = "y" });
            await lease.Db.SaveChangesAsync();
        }

        using var second = database.NewContext();
        second.Db.Add(new Job { OrganizationId = org, Type = "application.deploy", IdempotencyKey = key });
        await AssertConstraintAsync(() => second.Db.SaveChangesAsync(), UniqueViolation);
    }

    [RequiresDatabaseFact]
    public async Task LogChunks_AreKeyedByStreamAndSequence_AndReplayIsIdempotentInSql()
    {
        var streamId = "deploy:" + Guid.CreateVersion7();
        using (var lease = database.NewContext())
        {
            lease.Db.Add(new LogChunk { StreamId = streamId, Sequence = 2, Source = LogSource.Deploy, Stream = LogStream.Stderr, Data = "warn" });
            lease.Db.Add(new LogChunk { StreamId = streamId, Sequence = 1, Source = LogSource.Deploy, Stream = LogStream.Stdout, Data = "hello" });
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            var chunks = await lease.Db.LogChunks.Where(c => c.StreamId == streamId).OrderBy(c => c.Sequence).ToListAsync();
            Assert.Equal(["hello", "warn"], chunks.Select(c => c.Data));
            Assert.Equal(LogStream.Stderr, chunks[1].Stream);

            var smallint = await lease.Db.Database
                .SqlQueryRaw<short>($"SELECT stream AS \"Value\" FROM log_chunks WHERE stream_id = '{streamId}' AND sequence = 2")
                .SingleAsync();
            Assert.Equal((short)2, smallint);

            // ADR 0004 ingest: replay after reconnect must not fail or duplicate.
            var inserted = await lease.Db.Database.ExecuteSqlRawAsync(
                $"INSERT INTO log_chunks (stream_id, sequence, ts, source, stream, data) VALUES ('{streamId}', 1, now(), 2, 1, 'dup') ON CONFLICT (stream_id, sequence) DO NOTHING");
            Assert.Equal(0, inserted);
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(new LogChunk { StreamId = streamId, Sequence = 1, Data = "dup" });
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task JoinTokens_AreSingleUseByHash_AndTtlIsBounded()
    {
        var seed = await SeedBaseAsync();
        var hash = System.Security.Cryptography.SHA256.HashData(Guid.NewGuid().ToByteArray());
        using (var lease = database.NewContext())
        {
            lease.Db.Add(JoinToken.Issue(seed.ServerId, hash, DateTimeOffset.UtcNow, createdByUserId: seed.UserId));
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(JoinToken.Issue(seed.ServerId, hash, DateTimeOffset.UtcNow));
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }

        // The atomic consume statement from ADR 0002.
        using (var lease = database.NewContext())
        {
            const string consume =
                "UPDATE join_tokens SET used_at = now() WHERE token_hash = {0} AND used_at IS NULL AND expires_at > now() RETURNING server_id AS \"Value\"";
            var first = await lease.Db.Database.SqlQueryRaw<Guid>(consume, hash).ToListAsync();
            var replay = await lease.Db.Database.SqlQueryRaw<Guid>(consume, hash).ToListAsync();
            Assert.Equal(seed.ServerId, Assert.Single(first));
            Assert.Empty(replay);
        }

        using (var lease = database.NewContext())
        {
            var tooLong = JoinToken.Issue(seed.ServerId, System.Security.Cryptography.SHA256.HashData([1]), DateTimeOffset.UtcNow, TimeSpan.FromHours(24));
            tooLong.ExpiresAt = tooLong.CreatedAt.AddHours(48);
            lease.Db.Add(tooLong);
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), CheckViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task AgentCertificates_RevocationIsASerialLookup_AndOnlyOneCaIsActive()
    {
        var seed = await SeedBaseAsync();
        var serial = Unique("serial");
        Guid caId;
        using (var lease = database.NewContext())
        {
            var ca = new CertificateAuthority
            {
                Name = "agent-ca", Subject = "CN=Aethera Agent CA", CertificatePem = "-----BEGIN CERTIFICATE-----", FingerprintSha256 = Unique("fp"),
                NotBefore = Now, NotAfter = Now.AddYears(10), PrivateKeyCiphertext = [1], PrivateKeyNonce = [2], WrappedDataKey = [3], WrappedDataKeyNonce = [4],
                IsActive = false,
            };
            lease.Db.Add(ca);
            lease.Db.Add(new AgentCertificate
            {
                ServerId = seed.ServerId, CertificateAuthority = ca, Serial = serial, FingerprintSha256 = Unique("fp"),
                SubjectUri = $"spiffe://aethera/server/{seed.ServerId}", NotBefore = Now, NotAfter = Now.AddDays(30),
            });
            await lease.Db.SaveChangesAsync();
            caId = ca.Id;
        }

        using (var lease = database.NewContext())
        {
            var cert = await lease.Db.AgentCertificates.SingleAsync(c => c.Serial == serial);
            cert.Revoke("reset agent", Now.AddDays(1));
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            Assert.True(await lease.Db.AgentCertificates.AnyAsync(c => c.Serial == serial && c.RevokedAt != null));

            lease.Db.Add(new AgentCertificate
            {
                ServerId = seed.ServerId, CertificateAuthorityId = caId, Serial = serial, FingerprintSha256 = "x", SubjectUri = "spiffe://x",
            });
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }

        CertificateAuthority NewCa(string fp) => new()
        {
            Name = "ca", Subject = "CN=x", CertificatePem = "pem", FingerprintSha256 = fp, PrivateKeyCiphertext = [1], PrivateKeyNonce = [2],
            WrappedDataKey = [3], WrappedDataKeyNonce = [4], IsActive = true,
        };

        using (var lease = database.NewContext())
        {
            lease.Db.Add(NewCa(Unique("fp")));
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(NewCa(Unique("fp")));
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation); // second active CA
        }
    }

    [RequiresDatabaseFact]
    public async Task DeploymentSteps_PersistAsCheckpointsAndFailureNamesTheStep()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);
        Guid id;
        using (var lease = database.NewContext())
        {
            var d = Deployment.Queue(appId, seed.EnvId, seed.ServerId, 1, DeploymentTrigger.Manual, Now);
            d.Start("{}", Now);
            d.BeginStep(DeploymentStep.Source, Now);
            d.CompleteStep(DeploymentStep.Source, Now.AddSeconds(1));
            d.SkipStep(DeploymentStep.Build, Now.AddSeconds(1));
            d.BeginStep(DeploymentStep.HealthCheck, Now.AddSeconds(5)).DetailsJson = """{"attempts":3}""";
            d.MarkFailed(DeploymentStep.HealthCheck, "health.timeout", "no 200 within 60s", Now.AddSeconds(65));
            lease.Db.Add(d);
            await lease.Db.SaveChangesAsync();
            id = d.Id;
        }

        using (var lease = database.NewContext())
        {
            var d = await lease.Db.Deployments.Include(x => x.Steps).SingleAsync(x => x.Id == id);
            Assert.Equal(DeploymentStatus.Failed, d.Status);
            Assert.Equal(DeploymentStep.HealthCheck, d.FailedStep);
            Assert.Equal("health.timeout", d.FailureCode);
            Assert.Equal(
                [(DeploymentStep.Source, StepStatus.Succeeded), (DeploymentStep.Build, StepStatus.Skipped), (DeploymentStep.HealthCheck, StepStatus.Failed)],
                d.Steps.OrderBy(x => x.Step).Select(x => (x.Step, x.Status)));
            Assert.Equal("health.timeout", d.Steps.Single(x => x.Step == DeploymentStep.HealthCheck).ErrorCode);

            var stored = await lease.Db.Database
                .SqlQueryRaw<string>($"SELECT step AS \"Value\" FROM deployment_steps WHERE deployment_id = '{id}' ORDER BY started_at, step")
                .ToListAsync();
            Assert.Contains("healthCheck", stored);
        }
    }

    [RequiresDatabaseFact]
    public async Task SecretVersions_AreKeptPerSecret_AndDeletingASecretRemovesThem()
    {
        var seed = await SeedBaseAsync();
        Guid id;
        using (var lease = database.NewContext())
        {
            var secret = NewSecret(seed.OrgId, Unique("DB_PASSWORD"));
            secret.AddVersion([4], new byte[12], [5], new byte[12], masterKeyVersion: 2, Now.AddDays(1));
            lease.Db.Add(secret);
            await lease.Db.SaveChangesAsync();
            id = secret.Id;
        }

        using (var lease = database.NewContext())
        {
            var secret = await lease.Db.Secrets.Include(s => s.Versions).SingleAsync(s => s.Id == id);
            Assert.Equal(2, secret.CurrentVersion);
            Assert.Equal([1, 2], secret.Versions.Select(v => v.Version).Order());
            Assert.Equal(2, secret.Versions.Single(v => v.Version == 2).MasterKeyVersion);

            await lease.Db.Database.ExecuteSqlRawAsync($"DELETE FROM secrets WHERE id = '{id}'");
            Assert.False(await lease.Db.SecretVersions.AnyAsync(v => v.SecretId == id));
        }
    }

    [RequiresDatabaseFact]
    public async Task WebhookDeliveries_AreIdempotentPerEndpointAndDeliveryId()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);
        Guid endpointId;
        using (var lease = database.NewContext())
        {
            var endpoint = new WebhookEndpoint { WorkloadId = appId, Secret = NewSecret(seed.OrgId, Unique("whsec")) };
            lease.Db.Add(endpoint);
            lease.Db.Add(new WebhookDelivery { EndpointId = endpoint.Id, DeliveryId = "gh-1", SignatureValid = true, Outcome = WebhookOutcome.Accepted });
            await lease.Db.SaveChangesAsync();
            endpointId = endpoint.Id;
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(new WebhookDelivery { EndpointId = endpointId, DeliveryId = "gh-1", Outcome = WebhookOutcome.Duplicate });
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task IdempotencyRecordsAndSettings_RoundTrip()
    {
        var principal = Guid.CreateVersion7();
        var key = Unique("key");
        using (var lease = database.NewContext())
        {
            lease.Db.Add(new IdempotencyRecord
            {
                PrincipalId = principal, Key = key, Method = "POST", Path = "/api/v1/applications/x/deploy",
                RequestHash = System.Security.Cryptography.SHA256.HashData([1]), ExpiresAt = Now.AddHours(24),
            });
            lease.Db.Add(new InstanceSetting { Key = Unique("update.channel"), ValueJson = "\"stable\"" });
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            var record = await lease.Db.IdempotencyRecords.SingleAsync(r => r.PrincipalId == principal && r.Key == key);
            Assert.Equal(IdempotencyState.InProgress, record.State);
            record.State = IdempotencyState.Completed;
            record.ResponseStatus = 202;
            record.ResponseBody = "{\"id\":1}"u8.ToArray();
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            lease.Db.Add(new IdempotencyRecord
            {
                PrincipalId = principal, Key = key, Method = "POST", Path = "/other", RequestHash = new byte[32], ExpiresAt = Now,
            });
            await AssertConstraintAsync(() => lease.Db.SaveChangesAsync(), UniqueViolation);
        }
    }

    [RequiresDatabaseFact]
    public async Task MetricSamples_StoreServerAndContainerSeries()
    {
        var seed = await SeedBaseAsync();
        using (var lease = database.NewContext())
        {
            lease.Db.AddRange(
                new MetricSample { ServerId = seed.ServerId, Timestamp = Now, CpuPercent = 12.5, MemoryUsedBytes = 100, MemoryTotalBytes = 200 },
                new MetricSample { ServerId = seed.ServerId, Timestamp = Now, ContainerId = "abc", CpuPercent = 3, Resolution = MetricResolution.FiveMinutes });
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            var raw = await lease.Db.MetricSamples
                .Where(m => m.ServerId == seed.ServerId && m.Resolution == MetricResolution.Raw && m.Timestamp >= Now.AddMinutes(-1))
                .ToListAsync();
            var sample = Assert.Single(raw);
            Assert.Null(sample.ContainerId);
            Assert.Equal(12.5, sample.CpuPercent);
            Assert.True(sample.Id > 0);
        }
    }

    [RequiresDatabaseFact]
    public async Task ServerWithWorkloads_CannotBeHardDeleted()
    {
        var seed = await SeedBaseAsync();
        await SeedAppAsync(seed);

        using var lease = database.NewContext();
        var ex = await Assert.ThrowsAsync<PostgresException>(() =>
            lease.Db.Database.ExecuteSqlRawAsync($"DELETE FROM servers WHERE id = '{seed.ServerId}'"));
        Assert.Equal("23503", ex.SqlState);
    }

    [RequiresDatabaseFact]
    public async Task DeletingAProject_CascadesToItsWorkloadTree()
    {
        var seed = await SeedBaseAsync();
        var appId = await SeedAppAsync(seed);
        using (var lease = database.NewContext())
        {
            lease.Db.Add(new EnvironmentVariable { WorkloadId = appId, Key = "A", Value = "1" });
            lease.Db.Add(Deployment.Queue(appId, seed.EnvId, seed.ServerId, 1, DeploymentTrigger.Manual, Now));
            await lease.Db.SaveChangesAsync();
        }

        using (var lease = database.NewContext())
        {
            await lease.Db.Database.ExecuteSqlRawAsync($"DELETE FROM projects WHERE id = '{seed.ProjectId}'");
            Assert.False(await lease.Db.Workloads.IgnoreQueryFilters().AnyAsync(w => w.Id == appId));
            Assert.False(await lease.Db.EnvironmentVariables.AnyAsync(v => v.WorkloadId == appId));
            Assert.False(await lease.Db.Deployments.AnyAsync(d => d.WorkloadId == appId));
        }
    }
}
