using System.Text;
using System.Text.RegularExpressions;
using Aethera.Domain.Transport;

namespace Aethera.Engine.Proxy;

/// <summary>Traefik v3 with the Docker provider and Let's Encrypt HTTP-01 (spec section 12).</summary>
public sealed partial class TraefikProxyProvider : IProxyProvider
{
    public const string CertResolver = "letsencrypt";

    public string Name => "traefik";

    [GeneratedRegex(@"^(\*\.)?([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$|^localhost$")]
    private static partial Regex HostRegex();

    [GeneratedRegex(@"^[a-z0-9][a-z0-9_-]{0,62}$")]
    private static partial Regex NameRegex();

    [GeneratedRegex(@"^/[A-Za-z0-9._~/-]*$")]
    private static partial Regex PathRegex();

    public static bool IsValidHost(string host) => HostRegex().IsMatch(host);

    public ProxyEnsureCommand BuildEnsureCommand(ProxySettings settings)
    {
        var yaml = new StringBuilder();
        yaml.AppendLine("# Generated by Aethera. Edit through the API; manual changes are overwritten.");
        yaml.AppendLine("entryPoints:");
        yaml.AppendLine("  web:");
        yaml.AppendLine("    address: \":80\"");
        yaml.AppendLine("  websecure:");
        yaml.AppendLine("    address: \":443\"");
        yaml.AppendLine("providers:");
        yaml.AppendLine("  docker:");
        yaml.AppendLine("    exposedByDefault: false");
        yaml.AppendLine($"    network: {settings.Network}");
        yaml.AppendLine("    watch: true");
        if (settings.AcmeEmail is { Length: > 0 } email)
        {
            if (email.Any(c => char.IsWhiteSpace(c) || c is '"' or '\'' or '\\' or ':'))
                throw new ArgumentException("The ACME email contains characters that are not allowed.", nameof(settings));
            yaml.AppendLine("certificatesResolvers:");
            yaml.AppendLine($"  {CertResolver}:");
            yaml.AppendLine("    acme:");
            yaml.AppendLine($"      email: \"{email}\"");
            yaml.AppendLine("      storage: /acme/acme.json");
            if (settings.AcmeStaging)
                yaml.AppendLine("      caServer: https://acme-staging-v02.api.letsencrypt.org/directory");
            yaml.AppendLine("      httpChallenge:");
            yaml.AppendLine("        entryPoint: web");
        }
        yaml.AppendLine("api:");
        yaml.AppendLine("  dashboard: false");
        yaml.AppendLine("log:");
        yaml.AppendLine("  level: INFO");
        yaml.AppendLine("accessLog: {}");

        return new ProxyEnsureCommand("traefik", Encoding.UTF8.GetBytes(yaml.ToString()), Version: settings.Version, Network: settings.Network);
    }

    public IReadOnlyDictionary<string, string> RouteLabels(RouteSpec route)
    {
        if (route.Hosts.Count == 0) return new Dictionary<string, string>();
        if (!NameRegex().IsMatch(route.Name)) throw new ArgumentException($"Invalid route name '{route.Name}'.", nameof(route));
        if (route.ContainerPort is < 1 or > 65535) throw new ArgumentException("Invalid container port.", nameof(route));
        foreach (var h in route.Hosts)
            if (!HostRegex().IsMatch(h)) throw new ArgumentException($"Invalid host name '{h}'.", nameof(route));
        if (route.PathPrefix is { } p && !PathRegex().IsMatch(p)) throw new ArgumentException("Invalid path prefix.", nameof(route));

        var rule = string.Join(" || ", route.Hosts.Select(h => $"Host(`{h}`)"));
        if (route.PathPrefix is { Length: > 1 } prefix) rule = $"({rule}) && PathPrefix(`{prefix}`)";

        var n = route.Name;
        var labels = new Dictionary<string, string>
        {
            ["traefik.enable"] = "true",
            ["traefik.docker.network"] = route.Network,
            [$"traefik.http.services.{n}.loadbalancer.server.port"] = route.ContainerPort.ToString(),
        };

        if (!route.Https)
        {
            labels[$"traefik.http.routers.{n}.rule"] = rule;
            labels[$"traefik.http.routers.{n}.entrypoints"] = "web";
            labels[$"traefik.http.routers.{n}.service"] = n;
            return labels;
        }

        labels[$"traefik.http.routers.{n}-http.rule"] = rule;
        labels[$"traefik.http.routers.{n}-http.entrypoints"] = "web";
        labels[$"traefik.http.routers.{n}-http.service"] = n;
        if (route.RedirectToHttps)
        {
            labels[$"traefik.http.middlewares.{n}-redirect.redirectscheme.scheme"] = "https";
            labels[$"traefik.http.middlewares.{n}-redirect.redirectscheme.permanent"] = "true";
            labels[$"traefik.http.routers.{n}-http.middlewares"] = $"{n}-redirect";
        }
        labels[$"traefik.http.routers.{n}-https.rule"] = rule;
        labels[$"traefik.http.routers.{n}-https.entrypoints"] = "websecure";
        labels[$"traefik.http.routers.{n}-https.service"] = n;
        labels[$"traefik.http.routers.{n}-https.tls"] = "true";
        labels[$"traefik.http.routers.{n}-https.tls.certresolver"] = CertResolver;
        return labels;
    }
}
